# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ML_projects',
                'doc_host': 'https://reutkeller.github.io',
                'git_url': 'https://github.com/reutkeller/ML_projects',
                'lib_path': 'ML_projects'},
  'syms': {'ML_projects.core': {'ML_projects.core.foo': ('core.html#foo', 'ML_projects/core.py')}}}
