# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/CONSTANTS.ipynb.

# %% auto 0
__all__ = ['RANDOM_STATE', 'N_JOBS', 'VERBOSE', 'RANDOM_GRID_RFR', 'N_ITERATIONS_RFR', 'CV_RFR']

# %% ../nbs/CONSTANTS.ipynb 3
RANDOM_STATE = 42 
N_JOBS = -1 
VERBOSE = 1

# %% ../nbs/CONSTANTS.ipynb 4
RANDOM_GRID_RFR={'bootstrap': [True, False],
                'max_depth': [20, 40, 70, 80],
                'max_features': ['auto', 'sqrt'],
                'min_samples_leaf': [1, 2, 4],
                'min_samples_split': [2, 5, 10],
                'n_estimators': [200, 400, 600, 800]}


N_ITERATIONS_RFR = 100
CV_RFR = 3

