# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/data_exploration.ipynb.

# %% auto 0
__all__ = ['DataExploration']

# %% ../nbs/data_exploration.ipynb 3
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from . import const_vals as CONST


# %% ../nbs/data_exploration.ipynb 4
class DataExploration():


  def __init__(self,
               path_to_data : str , #path to read the data the will be analyzied 
               cols_for_analysis: list , # list with columns to be analysed
               ):
    

    self.cols_for_analysis = cols_for_analysis

    # read the dataframe 
    try:
      self.df = pd.read_csv(path_to_data)

    except Exception as e:
      error_str = CONST.ERROR_READ_DF + str(e)
      print(error_str)

    
    for col in self.cols_for_analysis:

      self._generate_histogram_(col_name = col)



  def _generate_histogram_(self,
                           col_name : str , # column name to be useed for analysis
                           ):
    
    # Plot histogram
    plt.figure(figsize=(8, 6))
    plt.hist(self.df[col_name], bins=CONST.BINS_HIST, 
             color=CONST.COLOSR_HIST, 
             alpha=CONST.ALPHA_HIST)
    
   
    plt.title(CONST.TITLE_HIST + col_name)
    plt.xlabel(CONST.X_LABEL_HIST)
    plt.ylabel(CONST.Y_LABEL_HIST)
    plt.grid(CONST.TO_GRID)
    plt.show()



    



